### ISSUE TITLE
Integration With Latex export .

### ISSUE THREAD

**Issue by M1ndo** [jkitchin/ov-highlighter#14]
Thanks for this amazing package i really love it however it doesn't work latex export, would u consider adding the feature to ov-highlight ?

**Comment by jkitchin** [comment]
That is not likely to happen. It isn't generally possible I think. You would have to define export rules for each kind of highlight, and then make a preprocess function to modify the buffer with those before export. ov-highlight was an experiment in this direction, but not the final step for me.

scimax-editmarks is closer to what you are looking for, and does basically have that feature, and it is more robust than ov-highlight (at the expense of extra markup).
