### ISSUE TITLE
Using ov-highlight in org-mode is tricky

### ISSUE THREAD

**Issue by hisnawi** [jkitchin/ov-highlighter#2]
I use org-mode to take notes and ov-highlight to highlight important parts. However, I found that moving subtrees around or refiling them to other org-mode files invalidates any highlighting.

I understand that the ov-highlight use some metadata in the file to track these highlights based on the position in the file but that is becoming impractical for me to leverage.

Is there a way to have a separate package or improve this one to have the highlighting happen without metadata? Basically, when marking a region then use the highlight to include the *s at beginnings and ends of lines of that region?

That way the information is embedded in the text which gets translated by org-mode as "highlighted text" and is movable between org-files.

**Comment by jkitchin** [comment]
I don't think what you want is possible. I wouldn't expect the highlights to work with refiling or headline shuffling. Copy and paste works, but only by advising those functions to store the overlays.    It looks like similar advice would have to be developed for other functions used in refiling and  headline shuffling. The metadata is what makes the overlays persistent, and for this it doesn't matter if it is in the file or somewhere else.  I don't know another way to store relative positions that would be reliable. you might look into some of the other annotation modes in emacs. One of them might be more suitable.

**Comment by hisnawi** [comment]
Thanks
