### ISSUE TITLE
reloading the org file does not evaluate highlighting

### ISSUE THREAD

**Issue by Hagopian** [jkitchin/ov-highlighter#3]
Hello,

I just started using highlighting in scimax/org-mode under windows and it works great, but if I close emacs and re-open the org-file again the highlighting is not evaluated, although I'm confirming evaluation at the safety warning. Instead I have the following at the end of the org file.

\#  ov-highlight-data: KCgyMzU3IDIzNjAgKG92LXR5cGUgImdyZWVuIiBvdi1oaWdobGlnaHRlciB0IGZhY2UgKDpiYWNrZ3JvdW5kICJEYXJrb2xpdmVncmVlbjEiKSkpKQ==

 \# Local Variables:
 \# eval: (ov-highlight-load)
 \# End:

If I just kill the buffer and reopen the org file without closing emacs, highlighting is still perfectly fine.
Any Ideas how I can fix this? Or how I can evaluate the 'ov-ighlight-data' after the org file was opened?

Thanks
Hagen

**Comment by jkitchin** [comment]
It sounds like ov-highlight is not getting loaded on initialization. 

Can you add (require 'ov-highlight) to your init file? and see if it gets fixed?

**Comment by Hagopian** [comment]
Thanks John,

that fixes the issue!

Cheers Hagen
